// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // La CLI (migraciones, studio) usa DIRECT_URL cuando existe — Supabase
    // y proveedores similares necesitan saltarse el pooler para migrar.
    // La app en marcha no lee esto: src/lib/prisma.ts usa DATABASE_URL
    // (con pooler) directamente en tiempo de ejecución.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
