-- Catálogo de ejemplo (bar de tapas inventado) para producción — puramente
-- aditivo: nunca borra nada, todo con ON CONFLICT DO NOTHING sobre ids fijos,
-- así que aplicarla de más (o a mano) nunca duplica ni pisa datos reales.
-- Se aplica sobre el primer local existente (en la práctica, el único).
DO $$
DECLARE
  v_local_id TEXT;
BEGIN
  SELECT id INTO v_local_id FROM "locales" ORDER BY "createdAt" ASC LIMIT 1;
  IF v_local_id IS NULL THEN
    RETURN;
  END IF;

  -- Categorías de carta
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-cervezas', v_local_id, 'Cervezas', 0) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-vinos-y-vermut', v_local_id, 'Vinos y Vermut', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-copas-y-combinados', v_local_id, 'Copas y Combinados', 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-refrescos-y-aguas', v_local_id, 'Refrescos y Aguas', 3) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-cafes-e-infusiones', v_local_id, 'Cafés e Infusiones', 4) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-tapas-frias', v_local_id, 'Tapas Frías', 5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-tapas-calientes', v_local_id, 'Tapas Calientes', 6) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "categorias_carta" ("id", "localId", "nombre", "orden") VALUES ('cat-montaditos-y-bocadillos', v_local_id, 'Montaditos y Bocadillos', 7) ON CONFLICT ("id") DO NOTHING;

  -- Referencias de inventario
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-cerveza-barril', v_local_id, 'Cerveza barril', 'l', 60, 15, 5, 20, 1.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-cerveza-sin-alcohol', v_local_id, 'Cerveza sin alcohol (botellín)', 'unidad', 48, 12, 6, 24, 0.65) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-vino-tinto', v_local_id, 'Vino tinto', 'l', 20, 4, 3, 8, 3.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-vino-blanco', v_local_id, 'Vino blanco', 'l', 15, 3, 2, 6, 3.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-vino-rosado', v_local_id, 'Vino rosado', 'l', 10, 2, 2, 5, 3.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-cava', v_local_id, 'Cava', 'l', 9, 1.5, 1, 3, 6) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-vermut', v_local_id, 'Vermut de grifo', 'l', 12, 3, 2, 6, 2.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-ron', v_local_id, 'Ron', 'l', 10, 1.5, 1, 3, 12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-ginebra', v_local_id, 'Ginebra', 'l', 10, 1.5, 1, 3, 14) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-whisky', v_local_id, 'Whisky', 'l', 7, 1, 1, 3, 16) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-refresco-cola', v_local_id, 'Refresco de cola', 'l', 15, 2, 2, 6, 0.9) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-refresco-naranja', v_local_id, 'Refresco de naranja', 'l', 12, 2, 2, 5, 0.9) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-refresco-limon', v_local_id, 'Refresco de limón', 'l', 12, 2, 2, 5, 0.9) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-tonica', v_local_id, 'Tónica (botellín)', 'unidad', 36, 8, 4, 15, 0.75) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-agua-mineral', v_local_id, 'Agua mineral (botella 50cl)', 'unidad', 48, 12, 6, 24, 0.4) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-cafe-grano', v_local_id, 'Café en grano', 'kg', 5, 0.8, 0.3, 1, 18) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-leche', v_local_id, 'Leche', 'l', 10, 2, 1, 4, 0.95) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-zumo-naranja', v_local_id, 'Zumo de naranja natural', 'l', 8, 1.5, 1, 3, 1.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-sidra', v_local_id, 'Sidra (botella)', 'unidad', 24, 6, 3, 12, 2.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-patatas', v_local_id, 'Patatas', 'kg', 25, 5, 3, 10, 0.9) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-aceite-oliva', v_local_id, 'Aceite de oliva', 'l', 10, 2, 1, 4, 4.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-huevos', v_local_id, 'Huevos', 'unidad', 120, 24, 12, 48, 0.22) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-jamon-serrano', v_local_id, 'Jamón serrano', 'kg', 6, 1.2, 0.5, 2, 22) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-queso-curado', v_local_id, 'Queso curado', 'kg', 5, 1, 0.5, 2, 14) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-pan', v_local_id, 'Pan (pieza)', 'unidad', 60, 12, 6, 24, 0.35) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-tomate', v_local_id, 'Tomate', 'kg', 10, 2, 1, 4, 1.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-pimiento-verde', v_local_id, 'Pimiento verde', 'kg', 6, 1.5, 0.5, 3, 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-calamar', v_local_id, 'Calamar (congelado)', 'kg', 8, 1.5, 0.5, 3, 9.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-boqueron', v_local_id, 'Boquerón en vinagre', 'kg', 4, 0.8, 0.3, 1.5, 11) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-croqueta', v_local_id, 'Croqueta (unidad)', 'unidad', 200, 40, 20, 80, 0.28) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-chorizo', v_local_id, 'Chorizo', 'kg', 5, 1, 0.5, 2, 9) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-morcilla', v_local_id, 'Morcilla', 'kg', 4, 0.8, 0.3, 1.5, 8.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-lomo', v_local_id, 'Lomo embuchado', 'kg', 4, 0.8, 0.3, 1.5, 16) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-pulpo', v_local_id, 'Pulpo cocido', 'kg', 3, 0.6, 0.2, 1, 28) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-champinon', v_local_id, 'Champiñón', 'kg', 6, 1.2, 0.5, 2.5, 3.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-salsa-brava', v_local_id, 'Salsa brava', 'l', 6, 1.2, 0.5, 2.5, 3.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-alioli', v_local_id, 'Alioli', 'l', 5, 1, 0.5, 2, 4) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-aceitunas', v_local_id, 'Aceitunas', 'kg', 6, 1.2, 0.5, 2.5, 3.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-anchoa', v_local_id, 'Anchoa en aceite', 'kg', 2, 0.4, 0.2, 0.8, 24) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-lechuga', v_local_id, 'Lechuga', 'kg', 5, 1, 0.5, 2, 1.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-atun-lata', v_local_id, 'Atún en lata', 'kg', 4, 0.8, 0.3, 1.5, 7.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-mahonesa', v_local_id, 'Mahonesa', 'l', 5, 1, 0.5, 2, 3.2) ON CONFLICT ("id") DO NOTHING;

  -- Productos de carta y su escandallo
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cana', v_local_id, 'cat-cervezas', 'Caña', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cana-receta-0', 'prod-cana', 'ing-cerveza-barril', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-tubo', v_local_id, 'cat-cervezas', 'Tubo', 2.6, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tubo-receta-0', 'prod-tubo', 'ing-cerveza-barril', 0.33) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-jarra', v_local_id, 'cat-cervezas', 'Jarra', 4.5, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-jarra-receta-0', 'prod-jarra', 'ing-cerveza-barril', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cerveza-sin', v_local_id, 'cat-cervezas', 'Cerveza sin alcohol', 2.4, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cerveza-sin-receta-0', 'prod-cerveza-sin', 'ing-cerveza-sin-alcohol', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-vino-tinto', v_local_id, 'cat-vinos-y-vermut', 'Copa de vino tinto', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-vino-tinto-receta-0', 'prod-vino-tinto', 'ing-vino-tinto', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-vino-blanco', v_local_id, 'cat-vinos-y-vermut', 'Copa de vino blanco', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-vino-blanco-receta-0', 'prod-vino-blanco', 'ing-vino-blanco', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-vino-rosado', v_local_id, 'cat-vinos-y-vermut', 'Copa de vino rosado', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-vino-rosado-receta-0', 'prod-vino-rosado', 'ing-vino-rosado', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cava', v_local_id, 'cat-vinos-y-vermut', 'Copa de cava', 2.8, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cava-receta-0', 'prod-cava', 'ing-cava', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-vermut', v_local_id, 'cat-vinos-y-vermut', 'Vermut', 2.5, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-vermut-receta-0', 'prod-vermut', 'ing-vermut', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-tinto-verano', v_local_id, 'cat-vinos-y-vermut', 'Tinto de verano', 2.5, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tinto-verano-receta-0', 'prod-tinto-verano', 'ing-vino-tinto', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tinto-verano-receta-1', 'prod-tinto-verano', 'ing-refresco-limon', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cubalibre', v_local_id, 'cat-copas-y-combinados', 'Cubalibre', 6, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cubalibre-receta-0', 'prod-cubalibre', 'ing-ron', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cubalibre-receta-1', 'prod-cubalibre', 'ing-refresco-cola', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-gintonic', v_local_id, 'cat-copas-y-combinados', 'Gin tonic', 7, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-gintonic-receta-0', 'prod-gintonic', 'ing-ginebra', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-gintonic-receta-1', 'prod-gintonic', 'ing-tonica', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-whisky-cola', v_local_id, 'cat-copas-y-combinados', 'Whisky con cola', 6.5, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-whisky-cola-receta-0', 'prod-whisky-cola', 'ing-whisky', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-whisky-cola-receta-1', 'prod-whisky-cola', 'ing-refresco-cola', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-refresco-cola', v_local_id, 'cat-refrescos-y-aguas', 'Refresco de cola', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-refresco-cola-receta-0', 'prod-refresco-cola', 'ing-refresco-cola', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-refresco-naranja', v_local_id, 'cat-refrescos-y-aguas', 'Refresco de naranja', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-refresco-naranja-receta-0', 'prod-refresco-naranja', 'ing-refresco-naranja', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-refresco-limon', v_local_id, 'cat-refrescos-y-aguas', 'Refresco de limón', 2.2, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-refresco-limon-receta-0', 'prod-refresco-limon', 'ing-refresco-limon', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-tonica', v_local_id, 'cat-refrescos-y-aguas', 'Tónica', 2.3, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tonica-receta-0', 'prod-tonica', 'ing-tonica', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-agua', v_local_id, 'cat-refrescos-y-aguas', 'Agua mineral', 1.6, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-agua-receta-0', 'prod-agua', 'ing-agua-mineral', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-zumo-naranja', v_local_id, 'cat-refrescos-y-aguas', 'Zumo de naranja natural', 2.8, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-zumo-naranja-receta-0', 'prod-zumo-naranja', 'ing-zumo-naranja', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-sidra', v_local_id, 'cat-refrescos-y-aguas', 'Sidra', 3.5, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-sidra-receta-0', 'prod-sidra', 'ing-sidra', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cafe-solo', v_local_id, 'cat-cafes-e-infusiones', 'Café solo', 1.4, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cafe-solo-receta-0', 'prod-cafe-solo', 'ing-cafe-grano', 0.007) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cafe-cortado', v_local_id, 'cat-cafes-e-infusiones', 'Café cortado', 1.5, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cafe-cortado-receta-0', 'prod-cafe-cortado', 'ing-cafe-grano', 0.007) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cafe-cortado-receta-1', 'prod-cafe-cortado', 'ing-leche', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-cafe-leche', v_local_id, 'cat-cafes-e-infusiones', 'Café con leche', 1.6, 'BEBIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cafe-leche-receta-0', 'prod-cafe-leche', 'ing-cafe-grano', 0.007) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-cafe-leche-receta-1', 'prod-cafe-leche', 'ing-leche', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-jamon-racion', v_local_id, 'cat-tapas-frias', 'Jamón serrano (ración)', 9.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-jamon-racion-receta-0', 'prod-jamon-racion', 'ing-jamon-serrano', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-tabla-quesos', v_local_id, 'cat-tapas-frias', 'Tabla de quesos', 8.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tabla-quesos-receta-0', 'prod-tabla-quesos', 'ing-queso-curado', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-tabla-iberica', v_local_id, 'cat-tapas-frias', 'Tabla ibérica', 12, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tabla-iberica-receta-0', 'prod-tabla-iberica', 'ing-jamon-serrano', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tabla-iberica-receta-1', 'prod-tabla-iberica', 'ing-chorizo', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tabla-iberica-receta-2', 'prod-tabla-iberica', 'ing-morcilla', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tabla-iberica-receta-3', 'prod-tabla-iberica', 'ing-queso-curado', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-aceitunas', v_local_id, 'cat-tapas-frias', 'Aceitunas aliñadas', 3, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-aceitunas-receta-0', 'prod-aceitunas', 'ing-aceitunas', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-banderillas', v_local_id, 'cat-tapas-frias', 'Banderillas', 3.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-banderillas-receta-0', 'prod-banderillas', 'ing-anchoa', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-banderillas-receta-1', 'prod-banderillas', 'ing-aceitunas', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-boquerones', v_local_id, 'cat-tapas-frias', 'Boquerones en vinagre', 6.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boquerones-receta-0', 'prod-boquerones', 'ing-boqueron', 0.12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-ensaladilla', v_local_id, 'cat-tapas-frias', 'Ensaladilla rusa', 5.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensaladilla-receta-0', 'prod-ensaladilla', 'ing-patatas', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensaladilla-receta-1', 'prod-ensaladilla', 'ing-atun-lata', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensaladilla-receta-2', 'prod-ensaladilla', 'ing-mahonesa', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensaladilla-receta-3', 'prod-ensaladilla', 'ing-huevos', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-pan-tomate', v_local_id, 'cat-tapas-frias', 'Pan con tomate', 3.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pan-tomate-receta-0', 'prod-pan-tomate', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pan-tomate-receta-1', 'prod-pan-tomate', 'ing-tomate', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pan-tomate-receta-2', 'prod-pan-tomate', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-ensalada-mixta', v_local_id, 'cat-tapas-frias', 'Ensalada mixta', 6.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensalada-mixta-receta-0', 'prod-ensalada-mixta', 'ing-lechuga', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensalada-mixta-receta-1', 'prod-ensalada-mixta', 'ing-tomate', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensalada-mixta-receta-2', 'prod-ensalada-mixta', 'ing-atun-lata', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-ensalada-mixta-receta-3', 'prod-ensalada-mixta', 'ing-huevos', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-bravas', v_local_id, 'cat-tapas-calientes', 'Patatas bravas', 5.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-bravas-receta-0', 'prod-bravas', 'ing-patatas', 0.25) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-bravas-receta-1', 'prod-bravas', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-bravas-receta-2', 'prod-bravas', 'ing-salsa-brava', 0.04) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-alioli-patatas', v_local_id, 'cat-tapas-calientes', 'Patatas alioli', 5.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-alioli-patatas-receta-0', 'prod-alioli-patatas', 'ing-patatas', 0.25) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-alioli-patatas-receta-1', 'prod-alioli-patatas', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-alioli-patatas-receta-2', 'prod-alioli-patatas', 'ing-alioli', 0.04) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-patatas-mixtas', v_local_id, 'cat-tapas-calientes', 'Patatas mixtas', 6, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-patatas-mixtas-receta-0', 'prod-patatas-mixtas', 'ing-patatas', 0.25) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-patatas-mixtas-receta-1', 'prod-patatas-mixtas', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-patatas-mixtas-receta-2', 'prod-patatas-mixtas', 'ing-salsa-brava', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-patatas-mixtas-receta-3', 'prod-patatas-mixtas', 'ing-alioli', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-tortilla-racion', v_local_id, 'cat-tapas-calientes', 'Tortilla de patatas (ración)', 6.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tortilla-racion-receta-0', 'prod-tortilla-racion', 'ing-patatas', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tortilla-racion-receta-1', 'prod-tortilla-racion', 'ing-huevos', 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-tortilla-racion-receta-2', 'prod-tortilla-racion', 'ing-aceite-oliva', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-pincho-tortilla', v_local_id, 'cat-tapas-calientes', 'Pincho de tortilla', 2.8, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pincho-tortilla-receta-0', 'prod-pincho-tortilla', 'ing-patatas', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pincho-tortilla-receta-1', 'prod-pincho-tortilla', 'ing-huevos', 0.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pincho-tortilla-receta-2', 'prod-pincho-tortilla', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-calamares', v_local_id, 'cat-tapas-calientes', 'Calamares a la romana', 9.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-calamares-receta-0', 'prod-calamares', 'ing-calamar', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-calamares-receta-1', 'prod-calamares', 'ing-aceite-oliva', 0.04) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-croquetas', v_local_id, 'cat-tapas-calientes', 'Croquetas de jamón (6u)', 7, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-croquetas-receta-0', 'prod-croquetas', 'ing-croqueta', 6) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-pulpo', v_local_id, 'cat-tapas-calientes', 'Pulpo a la gallega', 14, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pulpo-receta-0', 'prod-pulpo', 'ing-pulpo', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pulpo-receta-1', 'prod-pulpo', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-champinones', v_local_id, 'cat-tapas-calientes', 'Champiñones al ajillo', 6.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-champinones-receta-0', 'prod-champinones', 'ing-champinon', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-champinones-receta-1', 'prod-champinones', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-huevos-rotos', v_local_id, 'cat-tapas-calientes', 'Huevos rotos con jamón', 8.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-huevos-rotos-receta-0', 'prod-huevos-rotos', 'ing-huevos', 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-huevos-rotos-receta-1', 'prod-huevos-rotos', 'ing-patatas', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-huevos-rotos-receta-2', 'prod-huevos-rotos', 'ing-jamon-serrano', 0.06) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-huevos-rotos-receta-3', 'prod-huevos-rotos', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-pisto', v_local_id, 'cat-tapas-calientes', 'Pisto con huevo', 6.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pisto-receta-0', 'prod-pisto', 'ing-pimiento-verde', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pisto-receta-1', 'prod-pisto', 'ing-tomate', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pisto-receta-2', 'prod-pisto', 'ing-huevos', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-pisto-receta-3', 'prod-pisto', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-mont-jamon', v_local_id, 'cat-montaditos-y-bocadillos', 'Montadito de jamón', 2.2, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-jamon-receta-0', 'prod-mont-jamon', 'ing-pan', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-jamon-receta-1', 'prod-mont-jamon', 'ing-jamon-serrano', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-mont-chorizo', v_local_id, 'cat-montaditos-y-bocadillos', 'Montadito de chorizo', 2.2, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-chorizo-receta-0', 'prod-mont-chorizo', 'ing-pan', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-chorizo-receta-1', 'prod-mont-chorizo', 'ing-chorizo', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-mont-morcilla', v_local_id, 'cat-montaditos-y-bocadillos', 'Montadito de morcilla', 2.2, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-morcilla-receta-0', 'prod-mont-morcilla', 'ing-pan', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-morcilla-receta-1', 'prod-mont-morcilla', 'ing-morcilla', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-mont-queso', v_local_id, 'cat-montaditos-y-bocadillos', 'Montadito de queso', 2.2, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-queso-receta-0', 'prod-mont-queso', 'ing-pan', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-queso-receta-1', 'prod-mont-queso', 'ing-queso-curado', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-mont-lomo', v_local_id, 'cat-montaditos-y-bocadillos', 'Montadito de lomo', 2.3, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-lomo-receta-0', 'prod-mont-lomo', 'ing-pan', 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-mont-lomo-receta-1', 'prod-mont-lomo', 'ing-lomo', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-boc-jamon', v_local_id, 'cat-montaditos-y-bocadillos', 'Bocadillo de jamón', 5.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-jamon-receta-0', 'prod-boc-jamon', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-jamon-receta-1', 'prod-boc-jamon', 'ing-jamon-serrano', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-boc-calamares', v_local_id, 'cat-montaditos-y-bocadillos', 'Bocadillo de calamares', 6.5, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-calamares-receta-0', 'prod-boc-calamares', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-calamares-receta-1', 'prod-boc-calamares', 'ing-calamar', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-calamares-receta-2', 'prod-boc-calamares', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "productos" ("id", "localId", "categoriaId", "nombre", "precioVenta", "tipo") VALUES ('prod-boc-lomo', v_local_id, 'cat-montaditos-y-bocadillos', 'Bocadillo de lomo', 5.8, 'COMIDA') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-lomo-receta-0', 'prod-boc-lomo', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('prod-boc-lomo-receta-1', 'prod-boc-lomo', 'ing-lomo', 0.08) ON CONFLICT ("id") DO NOTHING;

  -- Proveedor y pedido de ejemplo, para probar Recepción sin crearlo a mano
  INSERT INTO "proveedores" ("id", "localId", "nombre", "contacto", "productosHabituales") VALUES ('prov-distribuciones-ebro', v_local_id, 'Distribuciones Ebro', '976 123 456', 'Cerveza, vino, refrescos') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "pedidos_proveedor" ("id", "proveedorId", "estado") VALUES ('pedido-ejemplo-ebro-1', 'prov-distribuciones-ebro', 'ENVIADO') ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "pedidos_proveedor_lineas" ("id", "pedidoId", "ingredienteId", "cantidad") VALUES ('pedido-ejemplo-ebro-1-l1', 'pedido-ejemplo-ebro-1', 'ing-cerveza-barril', 30) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "pedidos_proveedor_lineas" ("id", "pedidoId", "ingredienteId", "cantidad") VALUES ('pedido-ejemplo-ebro-1-l2', 'pedido-ejemplo-ebro-1', 'ing-vino-tinto', 10) ON CONFLICT ("id") DO NOTHING;
END $$;

