-- CreateEnum
CREATE TYPE "FormaMesa" AS ENUM ('REDONDA', 'RECTANGULAR');

-- AlterTable
ALTER TABLE "mesas"
  ALTER COLUMN "posicionX" SET DEFAULT 50,
  ALTER COLUMN "posicionY" SET DEFAULT 50,
  ADD COLUMN "forma" "FormaMesa" NOT NULL DEFAULT 'RECTANGULAR',
  ADD COLUMN "ancho" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN "alto" INTEGER NOT NULL DEFAULT 90;
