-- Escandallo de la carta real: liga cada uno de los 43 productos nuevos
-- (migración 20260904120000) con las referencias de inventario que lo
-- componen. Añade primero las ~35 referencias que la carta antigua no
-- tenía (marisco, torrezno, salmuera...); reutiliza las que ya existían
-- (patatas, huevos, aceite de oliva, jamón serrano, tomate...) cuando
-- encajan de verdad, en vez de duplicarlas con otro nombre.
DO $$
DECLARE
  v_local_id TEXT;
BEGIN
  SELECT id INTO v_local_id FROM "locales" ORDER BY "createdAt" ASC LIMIT 1;
  IF v_local_id IS NULL THEN
    RETURN;
  END IF;

  -- Referencias de inventario nuevas
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-vinagrillos', v_local_id, 'Vinagrillos (verduras encurtidas)', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 5.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-rejo', v_local_id, 'Rejo encurtido', 'COMIDA', 'kg', 3, 0.6, 0.2, 1, 9) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-alcachofa', v_local_id, 'Alcachofa', 'COMIDA', 'kg', 5, 1, 0.4, 2, 4.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-esparrago', v_local_id, 'Espárrago (frasco)', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 6.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-bonito-escabeche', v_local_id, 'Bonito en escabeche', 'COMIDA', 'kg', 3, 0.6, 0.2, 1, 8.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-torrezno', v_local_id, 'Torrezno (panceta)', 'COMIDA', 'kg', 5, 1, 0.4, 2, 7.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-bacalao', v_local_id, 'Bacalao desalado', 'COMIDA', 'kg', 6, 1.2, 0.5, 2.5, 12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-carioca', v_local_id, 'Carioca (unidad)', 'COMIDA', 'unidad', 100, 20, 10, 40, 0.45) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-croqueton', v_local_id, 'Croquetón (unidad)', 'COMIDA', 'unidad', 100, 20, 10, 40, 0.55) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-empanadilla-picante', v_local_id, 'Empanadilla carne picante (unidad)', 'COMIDA', 'unidad', 100, 20, 10, 40, 0.6) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-guacamole', v_local_id, 'Guacamole', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 6) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-ventresca', v_local_id, 'Ventresca de atún', 'COMIDA', 'kg', 3, 0.6, 0.2, 1, 26) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-piquillo', v_local_id, 'Pimiento del piquillo', 'COMIDA', 'kg', 5, 1, 0.4, 2, 4.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-solomillo-cerdo', v_local_id, 'Solomillo de cerdo', 'COMIDA', 'kg', 6, 1.2, 0.5, 2.5, 11) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-pedro-ximenez', v_local_id, 'Vino Pedro Ximénez', 'COMIDA', 'l', 4, 0.8, 0.3, 1.5, 7) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-langostino', v_local_id, 'Langostino', 'COMIDA', 'kg', 5, 1, 0.4, 2, 18) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-ostra', v_local_id, 'Ostra (unidad)', 'COMIDA', 'unidad', 60, 12, 6, 24, 1.3) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-zamburina', v_local_id, 'Zamburiña', 'COMIDA', 'unidad', 80, 16, 8, 32, 0.95) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-marisco-salpicon', v_local_id, 'Mezcla de marisco cocido', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-navaja', v_local_id, 'Navaja (marisco)', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 13) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-chipiron', v_local_id, 'Chipirón', 'COMIDA', 'kg', 6, 1.2, 0.5, 2.5, 14) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-gamba-roja', v_local_id, 'Gamba roja', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 32) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-gambardina', v_local_id, 'Gambardina (unidad)', 'COMIDA', 'unidad', 150, 30, 15, 60, 0.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-uva', v_local_id, 'Uva', 'COMIDA', 'kg', 3, 0.6, 0.2, 1, 2.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-verduras-tempura', v_local_id, 'Verduras variadas (tempura)', 'COMIDA', 'kg', 5, 1, 0.4, 2, 3.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-pescadito-fritura', v_local_id, 'Pescadito variado (fritura)', 'COMIDA', 'kg', 5, 1, 0.4, 2, 8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-garbanzo', v_local_id, 'Garbanzo cocido', 'COMIDA', 'kg', 6, 1.2, 0.5, 2.5, 2.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-bogavante', v_local_id, 'Bogavante', 'COMIDA', 'kg', 2, 0.4, 0.2, 0.8, 38) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-gulas', v_local_id, 'Gulas', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 9.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-picadillo-soria', v_local_id, 'Picadillo de Soria (chorizo fresco)', 'COMIDA', 'kg', 4, 0.8, 0.3, 1.5, 8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-madeja', v_local_id, 'Madeja de ternasco', 'COMIDA', 'kg', 3, 0.6, 0.2, 1, 13) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-pechuga-pollo', v_local_id, 'Pechuga de pollo', 'COMIDA', 'kg', 6, 1.2, 0.5, 2.5, 6.5) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-especias-cajun', v_local_id, 'Especias cajún', 'COMIDA', 'kg', 1, 0.2, 0.1, 0.4, 12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-roquefort', v_local_id, 'Queso roquefort', 'COMIDA', 'kg', 3, 0.6, 0.2, 1, 19) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "ingredientes" ("id", "localId", "nombre", "tipo", "unidadMedida", "stockAlmacen", "stockBarra", "stockMinimoBarra", "stockMaximoBarra", "costeUnitario") VALUES ('ing-churrasco-ternera', v_local_id, 'Churrasco de ternera (pieza)', 'COMIDA', 'kg', 6, 1.2, 0.5, 2.5, 15.5) ON CONFLICT ("id") DO NOTHING;

  -- Escandallo: qué referencias y cuánta cantidad lleva cada producto
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-salmuera-hielo-aceitunas', 'prod-salmuera-hielo', 'ing-aceitunas', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-vinagrillos-vinagrillos', 'prod-vinagrillos', 'ing-vinagrillos', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-banderilla-rejo-rejo', 'prod-banderilla-rejo', 'ing-rejo', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-alcachofas-parrilla-alcachofa', 'prod-alcachofas-parrilla', 'ing-alcachofa', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-alcachofas-parrilla-esparrago', 'prod-alcachofas-parrilla', 'ing-esparrago', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-alcachofas-parrilla-aceite-oliva', 'prod-alcachofas-parrilla', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-boqueron-ajillo-boqueron', 'prod-boqueron-ajillo', 'ing-boqueron', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-boqueron-ajillo-aceite-oliva', 'prod-boqueron-ajillo', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-guardia-civil-anchoa', 'prod-guardia-civil', 'ing-anchoa', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-guardia-civil-aceitunas', 'prod-guardia-civil', 'ing-aceitunas', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-taco-escabeche-bonito-escabeche', 'prod-taco-escabeche', 'ing-bonito-escabeche', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-torrezno-torrezno', 'prod-torrezno', 'ing-torrezno', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bunuelitos-bacalao-bacalao', 'prod-bunuelitos-bacalao', 'ing-bacalao', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bunuelitos-bacalao-huevos', 'prod-bunuelitos-bacalao', 'ing-huevos', 0.3) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-carioca-carioca', 'prod-carioca', 'ing-carioca', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-croqueton-croqueton', 'prod-croqueton', 'ing-croqueton', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-empanadilla-picante-empanadilla-picante', 'prod-empanadilla-picante', 'ing-empanadilla-picante', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-med-patatas', 'prod-ensaladilla-med', 'ing-patatas', 0.12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-med-atun-lata', 'prod-ensaladilla-med', 'ing-atun-lata', 0.04) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-med-mahonesa', 'prod-ensaladilla-med', 'ing-mahonesa', 0.04) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-med-huevos', 'prod-ensaladilla-med', 'ing-huevos', 0.4) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-grande-patatas', 'prod-ensaladilla-grande', 'ing-patatas', 0.22) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-grande-atun-lata', 'prod-ensaladilla-grande', 'ing-atun-lata', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-grande-mahonesa', 'prod-ensaladilla-grande', 'ing-mahonesa', 0.07) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ensaladilla-grande-huevos', 'prod-ensaladilla-grande', 'ing-huevos', 0.8) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tomate-preparado-tomate', 'prod-tomate-preparado', 'ing-tomate', 0.25) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tomate-preparado-aceite-oliva', 'prod-tomate-preparado', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bacalao-guacamole-ensalada-bacalao', 'prod-bacalao-guacamole-ensalada', 'ing-bacalao', 0.12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bacalao-guacamole-ensalada-guacamole', 'prod-bacalao-guacamole-ensalada', 'ing-guacamole', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-trujalico-tomate', 'prod-trujalico', 'ing-tomate', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-trujalico-jamon-serrano', 'prod-trujalico', 'ing-jamon-serrano', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-trujalico-ventresca', 'prod-trujalico', 'ing-ventresca', 0.06) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-anchoas-pan', 'prod-tostada-anchoas', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-anchoas-anchoa', 'prod-tostada-anchoas', 'ing-anchoa', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-anchoas-boqueron', 'prod-tostada-anchoas', 'ing-boqueron', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-anchoas-piquillo', 'prod-tostada-anchoas', 'ing-piquillo', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-bacalao-guacamole-pan', 'prod-tostada-bacalao-guacamole', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-bacalao-guacamole-bacalao', 'prod-tostada-bacalao-guacamole', 'ing-bacalao', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-bacalao-guacamole-guacamole', 'prod-tostada-bacalao-guacamole', 'ing-guacamole', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-ventresca-pan', 'prod-tostada-ventresca', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-ventresca-ventresca', 'prod-tostada-ventresca', 'ing-ventresca', 0.06) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-ventresca-piquillo', 'prod-tostada-ventresca', 'ing-piquillo', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-solomillo-px-pan', 'prod-tostada-solomillo-px', 'ing-pan', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-solomillo-px-solomillo-cerdo', 'prod-tostada-solomillo-px', 'ing-solomillo-cerdo', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-tostada-solomillo-px-pedro-ximenez', 'prod-tostada-solomillo-px', 'ing-pedro-ximenez', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-crujiente-langostino-langostino', 'prod-crujiente-langostino', 'ing-langostino', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-ostra-ostra', 'prod-ostra', 'ing-ostra', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-zamburina-plancha-zamburina', 'prod-zamburina-plancha', 'ing-zamburina', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-salpicon-marisco-marisco-salpicon', 'prod-salpicon-marisco', 'ing-marisco-salpicon', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-navajitas-plancha-navaja', 'prod-navajitas-plancha', 'ing-navaja', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-chipirones-plancha-chipiron', 'prod-chipirones-plancha', 'ing-chipiron', 0.22) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-gamba-roja-plancha-gamba-roja', 'prod-gamba-roja-plancha', 'ing-gamba-roja', 0.16) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-papas-bravas-real-patatas', 'prod-papas-bravas-real', 'ing-patatas', 0.25) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-papas-bravas-real-salsa-brava', 'prod-papas-bravas-real', 'ing-salsa-brava', 0.04) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-papas-bravas-real-aceite-oliva', 'prod-papas-bravas-real', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-rabas-calamar-calamar', 'prod-rabas-calamar', 'ing-calamar', 0.22) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-rabas-calamar-aceite-oliva', 'prod-rabas-calamar', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-gambardinas-gambardina', 'prod-gambardinas', 'ing-gambardina', 10) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-migas-huevo-uva-pan', 'prod-migas-huevo-uva', 'ing-pan', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-migas-huevo-uva-huevos', 'prod-migas-huevo-uva', 'ing-huevos', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-migas-huevo-uva-uva', 'prod-migas-huevo-uva', 'ing-uva', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-migas-huevo-uva-aceite-oliva', 'prod-migas-huevo-uva', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-verduritas-tempura-verduras-tempura', 'prod-verduritas-tempura', 'ing-verduras-tempura', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-verduritas-tempura-aceite-oliva', 'prod-verduritas-tempura', 'ing-aceite-oliva', 0.02) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-fritura-mixta-calamar', 'prod-fritura-mixta', 'ing-calamar', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-fritura-mixta-boqueron', 'prod-fritura-mixta', 'ing-boqueron', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-fritura-mixta-pescadito-fritura', 'prod-fritura-mixta', 'ing-pescadito-fritura', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-fritura-mixta-aceite-oliva', 'prod-fritura-mixta', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-garbanzos-bogavante-garbanzo', 'prod-garbanzos-bogavante', 'ing-garbanzo', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-garbanzos-bogavante-bogavante', 'prod-garbanzos-bogavante', 'ing-bogavante', 0.08) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bacalao-tomate-huevo-bacalao', 'prod-bacalao-tomate-huevo', 'ing-bacalao', 0.12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bacalao-tomate-huevo-tomate', 'prod-bacalao-tomate-huevo', 'ing-tomate', 0.12) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-bacalao-tomate-huevo-huevos', 'prod-bacalao-tomate-huevo', 'ing-huevos', 1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-jamon-real-huevos', 'prod-huevos-rotos-jamon-real', 'ing-huevos', 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-jamon-real-patatas', 'prod-huevos-rotos-jamon-real', 'ing-patatas', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-jamon-real-jamon-serrano', 'prod-huevos-rotos-jamon-real', 'ing-jamon-serrano', 0.06) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-jamon-real-aceite-oliva', 'prod-huevos-rotos-jamon-real', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-gulas-huevos', 'prod-huevos-rotos-gulas', 'ing-huevos', 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-gulas-patatas', 'prod-huevos-rotos-gulas', 'ing-patatas', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-gulas-gulas', 'prod-huevos-rotos-gulas', 'ing-gulas', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-gulas-aceite-oliva', 'prod-huevos-rotos-gulas', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-picadillo-soria-huevos', 'prod-huevos-rotos-picadillo-soria', 'ing-huevos', 2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-picadillo-soria-patatas', 'prod-huevos-rotos-picadillo-soria', 'ing-patatas', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-picadillo-soria-picadillo-soria', 'prod-huevos-rotos-picadillo-soria', 'ing-picadillo-soria', 0.1) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-huevos-rotos-picadillo-soria-aceite-oliva', 'prod-huevos-rotos-picadillo-soria', 'ing-aceite-oliva', 0.03) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-madeja-patatas-madeja', 'prod-madeja-patatas', 'ing-madeja', 0.25) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-madeja-patatas-patatas', 'prod-madeja-patatas', 'ing-patatas', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-pollo-cajun-patatas-pechuga-pollo', 'prod-pollo-cajun-patatas', 'ing-pechuga-pollo', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-pollo-cajun-patatas-especias-cajun', 'prod-pollo-cajun-patatas', 'ing-especias-cajun', 0.01) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-pollo-cajun-patatas-patatas', 'prod-pollo-cajun-patatas', 'ing-patatas', 0.15) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-solomillo-roquefort-solomillo-cerdo', 'prod-solomillo-roquefort', 'ing-solomillo-cerdo', 0.2) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-solomillo-roquefort-roquefort', 'prod-solomillo-roquefort', 'ing-roquefort', 0.05) ON CONFLICT ("id") DO NOTHING;
  INSERT INTO "receta_lineas" ("id", "productoId", "ingredienteId", "cantidad") VALUES ('rl-churrasco-ternera-churrasco-ternera', 'prod-churrasco-ternera', 'ing-churrasco-ternera', 0.25) ON CONFLICT ("id") DO NOTHING;
END $$;

